title: Evergreen
description: A debug tool for Android TV devices
url: 'https://google.github.io/evergreen-checker'
repository: google/evergreen-checker
theme_color: '#9cc269'

author:
  name: Manas Tungare
  twitter: Manas

theme: null
include:
  - '*.txt'
  - .well-known
exclude:
  - '*.sh'
  - '*.yml'
  - CNAME
  - README.md
github:
  - metadata
